# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_subs": "00_core.ipynb",
         "get_bfiles_tuple": "00_core.ipynb",
         "dwidenoiseInputSpec": "00_core.ipynb",
         "dwidenoiseOutputSpec": "00_core.ipynb",
         "dwidenoise": "00_core.ipynb",
         "N4BiasFieldCorrectionInputSpec": "00_core.ipynb",
         "N4BiasFieldCorrectionOutputSpec": "00_core.ipynb",
         "N4BiasFieldCorrection": "00_core.ipynb",
         "dwipreprocInputSpec": "00_core.ipynb",
         "dwipreprocOutputSpec": "00_core.ipynb",
         "dwipreproc": "00_core.ipynb",
         "mask2seedtuple": "00_core.ipynb",
         "pipeline": "01_pipeline.ipynb"}

modules = ["core.py",
           "pipeline.py"]

doc_url = "https://axiezai.github.io/pipetography/"

git_url = "https://github.com/axiezai/pipetography/tree/master/"

def custom_doc_links(name): return None
