# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"bfiles2tuple": "pipetography.ipynb",
         "dwidenoiseInputSpec": "pipetography.ipynb",
         "dwidenoiseOutputSpec": "pipetography.ipynb",
         "dwidenoise": "pipetography.ipynb",
         "N4BiasFieldCorrectionInputSpec": "pipetography.ipynb",
         "N4BiasFieldCorrectionOutputSpec": "pipetography.ipynb",
         "N4BiasFieldCorrection": "pipetography.ipynb",
         "mask2seedtuple": "pipetography.ipynb"}

modules = ["pipetography.py"]

doc_url = "https://axiezai.github.io/pipetography/"

git_url = "https://github.com/axiezai/pipetography/tree/master/"

def custom_doc_links(name): return None
